name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: [self-hosted, amazon-linux-2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Updated to the latest version, future-proofing for Node.js 20

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Updated to a newer version
        with:
          terraform_version: 1.7.2  # Updated to match the Terraform version you're using

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
